spring.application.name=SecureTicketingAPI

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ticketing}
spring.datasource.username=${DB_USER:ticketing}
spring.datasource.password=${DB_PASSWORD:ticketing}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# set JWT_SECRET in production.
jwt.secret=${JWT_SECRET:dev-only-secret-change-me-in-production-please}
jwt.access-token-ttl=15m
jwt.refresh-token-ttl=7d
